### ISSUE TITLE
Bioconductor release checklist

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/gemma.R#38]
- [x] Documentation #35 
- [x] search endpoint, removal of the deprecated taxon search, including it's use in the vignette
- [x] multi-experimentalFactor resultSets
- [x] resolve the difference between https://dev.gemma.msl.ubc.ca/rest/v2/resultSets?datasets=442 and https://dev.gemma.msl.ubc.ca/rest/v2/datasets/442/analyses/differential possibly use the latter with the `get_differential_expression_values` instead to avoid missing results

**Comment by oganm** [comment]
multi-experimentalFactor resultSets are currently resolved by adding all possible permutations as a result. currently it is not possible to determine which factors are the real baselines and therefore won't be present in the differential expression results. 

one way to address that would be to try to access the differential expression results table when creating the table but this adds a large overhead. not doing this might be confusing to an end user

**Comment by oganm** [comment]
elected to access expression results only when needed.

**Comment by oganm** [comment]
the differential endpoints is used instead of the resultSets endpoint for `get_differential_expression_values`
